export const bonds = [
  {
    isin: 'INE040A08484',
    name: 'HDFC Capital',
    type: 'Secured NCD',
    rating: 'BBB-',
    ratingOutlook: 'Stable outlook',
    ratingAgency: 'CRISIL',
    ratingReviewedAt: '12 Aug 2024',
    ratingPrior: 'BBB',
    ratingChangeNote: 'Downgraded from BBB in Aug 2024 due to increased leverage',
    ytm: 11.4,
    coupon: 10.75,
    couponFreq: 'Monthly',
    minInvest: 10000,
    unitPrice: 1000,
    minUnits: 10,
    maturityShort: "Jan '27",
    maturityFull: 'Jan 2027',
    tenureMonths: 14,
    perPayoutPerMin: 95,
    totalPayouts: 14,
    issuerType: 'NBFC',
    security: 'Secured',
    listing: 'BSE',
    tax: 'As per slab',
    payoutSchedule: [
      { date: '15 Apr 2025', label: 'Next payout · in 28 days', amount: 95, isNext: true },
      { date: '15 May 2025', label: '2nd payout', amount: 95, isNext: false },
      { date: '15 Jun 2025', label: '3rd payout', amount: 95, isNext: false },
    ],
    financials: {
      auditedNote: 'FY24 audited · CRISIL rated',
      metrics: [
        { label: 'Revenue', value: '₹4,820 Cr', delta: '↑ 12%' },
        { label: 'Net profit', value: '₹398 Cr', delta: '↑ 8%' },
        { label: 'AUM', value: '₹38,400 Cr', delta: '↑ 14%' },
        { label: 'NPA ratio', value: '2.1%', delta: '↓ 0.3pp' },
      ],
      revenueTrend: {
        bars: [38, 48, 42, 60, 76],
        years: ['FY20', 'FY21', 'FY22', 'FY23', 'FY24'],
        latestValue: '₹4.8K Cr',
      },
      riskIndicators: [
        { name: 'Interest coverage', value: '2.4x', status: 'amber', statusLabel: 'Adequate', benchmark: 'Industry avg 3.1x' },
        { name: 'Debt-to-equity', value: '4.8x', status: 'red', statusLabel: 'High', benchmark: 'Industry avg 3.2x' },
        { name: 'Profit margin', value: '8.2%', status: 'green', statusLabel: 'Healthy', benchmark: 'Improving YoY' },
        { name: 'NPA ratio', value: '2.1%', status: 'green', statusLabel: 'In range', benchmark: 'Sector range 1.8–3.5%' },
      ],
      summary: 'HDFC Capital is a non-banking financial company with strong parentage from HDFC Group. The recent BBB- rating reflects increased borrowing to fund portfolio expansion. Profitability has improved 12% YoY despite tighter sector regulation.',
    },
  },
  {
    isin: 'INE306N07RH4',
    name: 'Tata Capital Fin',
    type: 'Secured NCD',
    rating: 'AA+',
    ratingOutlook: 'Stable outlook',
    ratingAgency: 'CRISIL',
    ratingReviewedAt: '04 Sep 2024',
    ytm: 9.8,
    coupon: 9.4,
    couponFreq: 'Monthly',
    minInvest: 10000,
    unitPrice: 1000,
    minUnits: 10,
    maturityShort: "Aug '26",
    maturityFull: 'Aug 2026',
    tenureMonths: 9,
    perPayoutPerMin: 79,
    totalPayouts: 9,
    issuerType: 'NBFC',
    security: 'Secured',
    listing: 'BSE',
    tax: 'As per slab',
    payoutSchedule: [
      { date: '20 Apr 2025', label: 'Next payout · in 33 days', amount: 79, isNext: true },
      { date: '20 May 2025', label: '2nd payout', amount: 79, isNext: false },
      { date: '20 Jun 2025', label: '3rd payout', amount: 79, isNext: false },
    ],
  },
  {
    isin: 'INE414G07HD8',
    name: 'Muthoot Finance',
    type: 'Secured NCD',
    rating: 'AA',
    ytm: 10.2,
    minInvest: 10000,
    couponFreq: 'Monthly',
    maturityShort: "Mar '27",
    tenureMonths: 16,
  },
  {
    isin: 'INE721A07OZ8',
    name: 'Shriram Finance',
    type: 'Secured NCD',
    rating: 'AA',
    ytm: 10.5,
    minInvest: 10000,
    couponFreq: 'Monthly',
    maturityShort: "Sep '26",
    tenureMonths: 10,
  },
];

export const orders = [
  {
    id: 'BSC-7821',
    bondIsin: 'INE040A08484',
    bondName: 'HDFC Capital',
    units: 10,
    amount: 10000,
    placedAt: '15 Mar, 2:14 PM',
    settledBy: '17 Mar',
    daysLeft: 2,
    timeline: [
      { label: 'Order placed', sub: '15 Mar, 2:14 PM', status: 'done' },
      { label: 'Funds received', sub: '15 Mar, 2:15 PM · UPI', status: 'done' },
      { label: 'Allotment in progress', sub: 'Issuer is processing your application', status: 'active' },
      { label: 'Settled to demat', sub: 'Expected by 17 Mar', status: 'pending' },
    ],
  },
];

export const portfolio = {
  totalValue: 40825,
  totalInvested: 40000,
  totalEarned: 825,
  avgYield: 10.6,
  deltaAmount: 825,
  deltaPercent: 2.06,
  nextPayout: { amount: 2400, days: 12 },
  cashflow: [
    { month: 'Apr', amount: 215, kind: 'coupon' },
    { month: 'May', amount: 215, kind: 'coupon' },
    { month: 'Jun', amount: 215, kind: 'coupon' },
    { month: 'Jul', amount: 815, kind: 'principal' },
    { month: 'Aug', amount: 215, kind: 'coupon' },
    { month: 'Sep', amount: 215, kind: 'coupon' },
    { month: 'Oct', amount: 215, kind: 'coupon' },
    { month: 'Nov', amount: 215, kind: 'coupon' },
    { month: 'Dec', amount: 215, kind: 'coupon' },
    { month: 'Jan', amount: 215, kind: 'coupon' },
    { month: 'Feb', amount: 215, kind: 'coupon' },
    { month: 'Mar', amount: 850, kind: 'principal' },
  ],
  holdings: [
    { isin: 'INE040A08484', name: 'HDFC Capital', units: 10, rating: 'BBB-', currentValue: 10415, gain: 415, nextPayout: { amount: 95, days: 12 } },
    { isin: 'INE306N07RH4', name: 'Tata Capital Fin', units: 15, rating: 'AA+', currentValue: 15210, gain: 210, nextPayout: { amount: 120, days: 22 } },
    { isin: 'INE414G07HD8', name: 'Muthoot Finance', units: 8, rating: 'AA', currentValue: 8200, gain: 200, nextPayout: { amount: 68, days: 4 } },
  ],
  pendingOrders: [{ id: 'BSC-7821', amount: 15000, daysLeft: 2 }],
};

export function getBond(isin: string) {
  return bonds.find((b) => b.isin === isin) || bonds[0];
}

export function getOrder(id: string) {
  return orders.find((o) => o.id === id) || orders[0];
}
